<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <AssemblyName>CSDebugDraw2D</AssemblyName>
    <RootNamespace>CSDebugDraw2D</RootNamespace>
    <PackageId>CSDebugDraw2D</PackageId>
    <Version>1.0.4</Version>
    <Authors>Lewis Allery</Authors>
    <Description>Debug drawing utilities for 2D scenes in Godot using C#.</Description>
    <PackageTags>godot;debug;draw;2d;visualization</PackageTags>
    <Company>Lewis Allery</Company>
    <RepositoryUrl>https://github.com/Lewis-Allery/CSGodotDebugDraw</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <!-- Enable NuGet packaging -->
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GodotSharp" Version="4.4.*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="CSDebugDraw2D.cs" />
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>